### ISSUE TITLE
Final feedback from Junior Proctor

### ISSUE THREAD

**Issue by jaredkhan** [hackersatcambridge/constitution#4]
Some requested changes from the Junior Proctor before final approval:

> 4. Executive Committee
> 
> 3. ……. who shall be a resident member of the Regent House

please take out resident (sorry my mistake!)

> 6. General Meetings

Please could you add a clause stating that:

"A majority of the elected members of the Executive Committee shall be
full-time undergraduate or post graduate students of the University of
Cambridge"

> 8. Changes to the Constitution and Repository

This should be titled "Changes to the Repository"
An additional point called "Changes to the Constitution" should be
added – it should be copied from that contained in the Notes for
guidance of Clubs and Societies, attached.

**Comment by moosichu** [comment]
Fixed ages ago by #7!
